### ISSUE TITLE
Can't install in windows 10 x64 on chromebook pixel 2013

### ISSUE THREAD

**Issue by JackeyGithub** [coolstar/croskeyboard3#1]
Thanks a lot first for your hard work. :+1: 
I compiled a version without signature with windows 8.1 WDK for windows 8 x64,  and install it on windows 10 x64 (disabled the windows's signature) from device manager, but the manger can't find the driver in the directory. Is there something missed in the inf file? or did I missing something?
I tried right clicking the inf and choose installing it, but after that, it still can't work, even after restart the computer.
My device hardware id is:
ACPI\VEN_GGL&DEV_0002
ACPI\GGL0002
*GGL0002

**Comment by coolstar** [comment]
You are missing an ACPI patch. See here http://community.acer.com/t5/Chromebooks/GUIDE-Install-Windows-8-on-the-Acer-C720/m-p/362276#M2033

Follow those instructions (but use croskeyboard3 instead of croskeyboard2)

**Comment by coolstar** [comment]
@JackeyGithub also, you can use this prebuilt binary: https://dl.dropboxusercontent.com/u/59964215/chromebook/x64/croskeyboard3.1.zip

It's testsigned so you can just "bcdedit -set testsigning on" and reboot rather than disabling signature enforcement on every boot
